name: Chromedriver updater

on:
  schedule:
    - cron: '30 5 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run update chromedriver script
        run: ./update_chromedriver.sh
