name: Chromedriver updater

on:
  schedule:
    - cron: '30 5 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run update chromedriver script
        run: |
          latest_version=$(curl "https://chromedriver.storage.googleapis.com/LATEST_RELEASE" --silent)
          current_version=$(cat ./chromedriver/version)
          if [ $latest_version = $current_version ]; then
            echo "You chromedriver is updated."
          else
            echo "Updating chromedriver..."
              rm chromedriver/chromedriver.exe
              rm chromedriver/version
              curl "https://chromedriver.storage.googleapis.com/$latest_version/chromedriver_win32.zip" > chromedriver/temp.zip
              cd chromedriver
              unzip -o temp.zip
              rm temp.zip
              echo $latest_version > version
              cd ..
              git config user.name "GitHub Actions Bot"
              git config user.email "<>"
              git add chromedriver/chromedriver.exe chromedriver/version
              git commit -m "Updating chromedriver version to $latest_version"
              git push origin staging
          fi
